name: Test

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
      - name: Setup Deno Runtime
        uses: denoland/setup-deno@v2
        with:
          deno-version: vx.x.x
          cache: true
      - name: Run Tests
        run: deno task test
